# This is some leading commentary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx

        # Comment
        image: "nginx:1.7.9" # Trailing comment
        ports:
        - containerPort: 80
